/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsSelectRouteImport } from './routes/programs/select'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs/$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSelectRoute = ProgramsSelectRouteImport.update({
  id: '/programs/select',
  path: '/programs/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/programs/select': typeof ProgramsSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/programs/select': typeof ProgramsSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/programs/select': typeof ProgramsSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programs/$programId' | '/programs/select'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programs/$programId' | '/programs/select'
  id: '__root__' | '/' | '/programs/$programId' | '/programs/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  ProgramsSelectRoute: typeof ProgramsSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/select': {
      id: '/programs/select'
      path: '/programs/select'
      fullPath: '/programs/select'
      preLoaderRoute: typeof ProgramsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  ProgramsSelectRoute: ProgramsSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
