version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels: ["dependencies"]
    groups:
      npm-and-yarn-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      npm-and-yarn-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      github-actions:
        patterns: ["*"]
