import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  createTableRelationsHelpers,
  extractTablesRelationalConfig,
} from "drizzle-orm/relations";
import { BaseSQLiteDatabase } from "drizzle-orm/sqlite-core";
import { printSchema } from "graphql";
import * as drizzleSchema from "../src/shared/schema";
import { buildAppSchema } from "../src/worker/routes/schema";

// Dumps the full GraphQL schema (drizzle-graphql auto entities + hand-written
// resolvers) to SDL, feeding graphql-codegen. buildAppSchema -> buildSchema
// only reads the static Drizzle schema (`db._.fullSchema`) and the relational
// query builders derived from it — no live D1 connection is required. This
// replicates drizzle()'s schema config so db.query is populated the same way
// the worker does. Regenerate on any schema change; CI diffs the committed
// graphql/schema.graphql.
//
// Type-checked by the worker project (tsconfig.worker.json) so `tsc -b` (the
// build) catches regressions in the schema generator; excluded from
// tsconfig.scripts.json because it pulls in the worker module graph.
const tablesConfig = extractTablesRelationalConfig(
  drizzleSchema,
  createTableRelationsHelpers,
);
const db = new BaseSQLiteDatabase(
  "sync",
  undefined as never,
  undefined as never,
  {
    fullSchema: drizzleSchema,
    schema: tablesConfig.tables,
    tableNamesMap: tablesConfig.tableNamesMap,
  },
);

const schema = buildAppSchema(db);

const outFile = path.join(
  import.meta.dirname,
  "..",
  "graphql",
  "schema.graphql",
);
const sdl = `# Generated by scripts/dump-schema.ts — do not edit by hand.
# Regenerate with: bun run schema:generate
${printSchema(schema)}
`;

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, sdl, "utf-8");

console.log(`Generated ${path.relative(process.cwd(), outFile)}`);
