name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v6

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork
        with:
          token: ${{ github.token }}
          environment: Preview (${{ github.head_ref }})
          initial-status: pending

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Run build
        run: pnpm build

      - name: Apply D1 Migrations
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork)
        run: >
          ${{ github.ref == 'refs/heads/main'
            && 'pnpm migrate:prod'
            || 'pnpm migrate:preview'
          }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare
        id: deploy
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            ${{ github.ref == 'refs/heads/main'
              && 'deploy'
              || 'versions upload --env preview'
            }}

      - name: Update Deployment (Success)
        uses: chrnorm/deployment-status@v2
        if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork && success()
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deploy.outputs.deployment-url }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update Deployment (Failure)
        uses: chrnorm/deployment-status@v2
        if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork && failure()
        with:
          token: ${{ github.token }}
          state: 'error'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
